import re

POSTAL_CODE_DATA = {
    'AD': {'name': 'Andorra', 'regex': r'^AD\d{3}$'},
    'AE': {'name': 'United Arab Emirates', 'regex': r'^$'},  # UAE typically does not use postal codes
    'AF': {'name': 'Afghanistan', 'regex': r'^\d{4}$'},
    'AL': {'name': 'Albania', 'regex': r'^\d{4}$'},
    'AM': {'name': 'Armenia', 'regex': r'^\d{4}$'},
    'AO': {'name': 'Angola', 'regex': r'^\d{4}$'},
    'AR': {'name': 'Argentina', 'regex': r'^[A-Z]\d{4}[A-Z]{3}$'},
    'AT': {'name': 'Austria', 'regex': r'^\d{4}$'},
    'AU': {'name': 'Australia', 'regex': r'^\d{4}$'},
    'AZ': {'name': 'Azerbaijan', 'regex': r'^\d{4}$'},
    'BA': {'name': 'Bosnia and Herzegovina', 'regex': r'^\d{5}$'},
    'BB': {'name': 'Barbados', 'regex': r'^$'},
    'BD': {'name': 'Bangladesh', 'regex': r'^\d{4}$'},
    'BE': {'name': 'Belgium', 'regex': r'^\d{4}$'},
    'BF': {'name': 'Burkina Faso', 'regex': r'^$'},
    'BG': {'name': 'Bulgaria', 'regex': r'^\d{4}$'},
    'BH': {'name': 'Bahrain', 'regex': r'^(\d{3}|\d{4})$'},
    'BI': {'name': 'Burundi', 'regex': r'^$'},
    'BJ': {'name': 'Benin', 'regex': r'^\d{5}$'},
    'BN': {'name': 'Brunei', 'regex': r'^$'},
    'BO': {'name': 'Bolivia', 'regex': r'^\d{5}$'},
    'BR': {'name': 'Brazil', 'regex': r'^\d{5}-\d{3}$'},
    'BS': {'name': 'Bahamas', 'regex': r'^$'},
    'BT': {'name': 'Bhutan', 'regex': r'^\d{5}$'},
    'BW': {'name': 'Botswana', 'regex': r'^\d{3}$'},
    'BY': {'name': 'Belarus', 'regex': r'^\d{6}$'},
    'BZ': {'name': 'Belize', 'regex': r'^$'},
    'CA': {'name': 'Canada', 'regex': r'^[A-Za-z]\d[A-Za-z][ -]?\d[A-Za-z]\d$'},
    'CF': {'name': 'Central African Republic', 'regex': r'^$'},
    'CG': {'name': 'Congo (Brazzaville)', 'regex': r'^$'},
    'CH': {'name': 'Switzerland', 'regex': r'^\d{4}$'},
    'CI': {'name': "Côte d'Ivoire", 'regex': r'^\d{5}$'},
    'CL': {'name': 'Chile', 'regex': r'^\d{7}$'},
    'CM': {'name': 'Cameroon', 'regex': r'^$'},
    'CN': {'name': 'China', 'regex': r'^\d{6}$'},
    'CO': {'name': 'Colombia', 'regex': r'^\d{6}$'},
    'CR': {'name': 'Costa Rica', 'regex': r'^\d{4}$'},
    'CU': {'name': 'Cuba', 'regex': r'^\d{5}$'},
    'CV': {'name': 'Cape Verde', 'regex': r'^\d{4}$'},
    'CY': {'name': 'Cyprus', 'regex': r'^\d{4}$'},
    'CZ': {'name': 'Czech Republic', 'regex': r'^\d{3}\s?\d{2}$'},
    'DE': {'name': 'Germany', 'regex': r'^\d{5}$'},
    'DK': {'name': 'Denmark', 'regex': r'^\d{4}$'},
    'DO': {'name': 'Dominican Republic', 'regex': r'^\d{5}$'},
    'DZ': {'name': 'Algeria', 'regex': r'^\d{5}$'},
    'EC': {'name': 'Ecuador', 'regex': r'^\d{6}$'},
    'EE': {'name': 'Estonia', 'regex': r'^\d{5}$'},
    'EG': {'name': 'Egypt', 'regex': r'^\d{5}$'},
    'ER': {'name': 'Eritrea', 'regex': r'^$'},
    'ES': {'name': 'Spain', 'regex': r'^\d{5}$'},
    'ET': {'name': 'Ethiopia', 'regex': r'^\d{4}$'},
    'FI': {'name': 'Finland', 'regex': r'^\d{5}$'},
    'FJ': {'name': 'Fiji', 'regex': r'^$'},
    'FR': {'name': 'France', 'regex': r'^\d{5}$'},
    'GA': {'name': 'Gabon', 'regex': r'^$'},
    'GB': {'name': 'United Kingdom', 'regex': r'^(GIR ?0AA|[A-Z]{1,2}\d{1,2}[A-Z]?\s*\d[A-Z]{2})$'},
    'GE': {'name': 'Georgia', 'regex': r'^\d{4}$'},
    'GH': {'name': 'Ghana', 'regex': r'^\d{5}$'},
    'GM': {'name': 'Gambia', 'regex': r'^$'},
    'GN': {'name': 'Guinea', 'regex': r'^$'},
    'GQ': {'name': 'Equatorial Guinea', 'regex': r'^$'},
    'GR': {'name': 'Greece', 'regex': r'^\d{5}$'},
    'GT': {'name': 'Guatemala', 'regex': r'^\d{5}$'},
    'GW': {'name': 'Guinea-Bissau', 'regex': r'^$'},
    'GY': {'name': 'Guyana', 'regex': r'^$'},
    'HN': {'name': 'Honduras', 'regex': r'^\d{5}$'},
    'HR': {'name': 'Croatia', 'regex': r'^\d{5}$'},
    'HT': {'name': 'Haiti', 'regex': r'^$'},
    'HU': {'name': 'Hungary', 'regex': r'^\d{4}$'},
    'ID': {'name': 'Indonesia', 'regex': r'^\d{5}$'},
    'IE': {'name': 'Ireland', 'regex': r'^[A-Za-z0-9]{3,4}$'},
    'IL': {'name': 'Israel', 'regex': r'^\d{7}$'},
    'IN': {'name': 'India', 'regex': r'^\d{6}$'},
    'IQ': {'name': 'Iraq', 'regex': r'^\d{5}$'},
    'IR': {'name': 'Iran', 'regex': r'^\d{10}$'},
    'IS': {'name': 'Iceland', 'regex': r'^\d{3}$'},
    'IT': {'name': 'Italy', 'regex': r'^\d{5}$'},
    'JM': {'name': 'Jamaica', 'regex': r'^$'},
    'JO': {'name': 'Jordan', 'regex': r'^\d{5}$'},
    'JP': {'name': 'Japan', 'regex': r'^\d{3}-\d{4}$'},
    'KE': {'name': 'Kenya', 'regex': r'^\d{5}$'},
    'KG': {'name': 'Kyrgyzstan', 'regex': r'^\d{6}$'},
    'KH': {'name': 'Cambodia', 'regex': r'^\d{5}$'},
    'KI': {'name': 'Kiribati', 'regex': r'^$'},
    'KM': {'name': 'Comoros', 'regex': r'^$'},
    'KN': {'name': 'Saint Kitts and Nevis', 'regex': r'^$'},
    'KP': {'name': 'North Korea', 'regex': r'^$'},
    'KR': {'name': 'South Korea', 'regex': r'^\d{5}$'},
    'KW': {'name': 'Kuwait', 'regex': r'^\d{5}$'},
    'KZ': {'name': 'Kazakhstan', 'regex': r'^\d{6}$'},
    'LA': {'name': 'Laos', 'regex': r'^\d{5}$'},
    'LB': {'name': 'Lebanon', 'regex': r'^\d{4}$'},
    'LC': {'name': 'Saint Lucia', 'regex': r'^$'},
    'LI': {'name': 'Liechtenstein', 'regex': r'^\d{4}$'},
    'LK': {'name': 'Sri Lanka', 'regex': r'^\d{5}$'},
    'LR': {'name': 'Liberia', 'regex': r'^$'},
    'LS': {'name': 'Lesotho', 'regex': r'^\d{3}$'},
    'LT': {'name': 'Lithuania', 'regex': r'^\d{5}$'},
    'LU': {'name': 'Luxembourg', 'regex': r'^\d{4}$'},
    'LV': {'name': 'Latvia', 'regex': r'^\d{4}$'},
    'LY': {'name': 'Libya', 'regex': r'^\d{5}$'},
    'MA': {'name': 'Morocco', 'regex': r'^\d{5}$'},
    'MC': {'name': 'Monaco', 'regex': r'^\d{5}$'},
    'MD': {'name': 'Moldova', 'regex': r'^\d{4}$'},
    'ME': {'name': 'Montenegro', 'regex': r'^\d{5}$'},
    'MG': {'name': 'Madagascar', 'regex': r'^$'},
    'MH': {'name': 'Marshall Islands', 'regex': r'^$'},
    'MK': {'name': 'North Macedonia', 'regex': r'^\d{4}$'},
    'ML': {'name': 'Mali', 'regex': r'^$'},
    'MM': {'name': 'Myanmar', 'regex': r'^\d{5}$'},
    'MN': {'name': 'Mongolia', 'regex': r'^\d{6}$'},
    'MO': {'name': 'Macao', 'regex': r'^$'},
    'MR': {'name': 'Mauritania', 'regex': r'^\d{5}$'},
    'MT': {'name': 'Malta', 'regex': r'^\d{4}$'},
    'MU': {'name': 'Mauritius', 'regex': r'^\d{5}$'},
    'MV': {'name': 'Maldives', 'regex': r'^\d{5}$'},
    'MW': {'name': 'Malawi', 'regex': r'^$'},
    'MX': {'name': 'Mexico', 'regex': r'^\d{5}$'},
    'MY': {'name': 'Malaysia', 'regex': r'^\d{5}$'},
    'MZ': {'name': 'Mozambique', 'regex': r'^\d{4}$'},
    'NA': {'name': 'Namibia', 'regex': r'^\d{4}$'},
    'NE': {'name': 'Niger', 'regex': r'^$'},
    'NG': {'name': 'Nigeria', 'regex': r'^\d{6}$'},
    'NI': {'name': 'Nicaragua', 'regex': r'^\d{5}$'},
    'NL': {'name': 'Netherlands', 'regex': r'^\d{4}\s?[A-Z]{2}$'},
    'NO': {'name': 'Norway', 'regex': r'^\d{4}$'},
    'NP': {'name': 'Nepal', 'regex': r'^\d{5}$'},
    'NR': {'name': 'Nauru', 'regex': r'^$'},
    'NZ': {'name': 'New Zealand', 'regex': r'^\d{4}$'},
    'OM': {'name': 'Oman', 'regex': r'^\d{3}$'},
    'PA': {'name': 'Panama', 'regex': r'^\d{4}$'},
    'PE': {'name': 'Peru', 'regex': r'^\d{5}$'},
    'PG': {'name': 'Papua New Guinea', 'regex': r'^$'},
    'PH': {'name': 'Philippines', 'regex': r'^\d{4}$'},
    'PK': {'name': 'Pakistan', 'regex': r'^\d{5}$'},
    'PL': {'name': 'Poland', 'regex': r'^\d{2}-\d{3}$'},
    'PT': {'name': 'Portugal', 'regex': r'^\d{4}-\d{3}$'},
    'PW': {'name': 'Palau', 'regex': r'^$'},
    'PY': {'name': 'Paraguay', 'regex': r'^\d{4}$'},
    'QA': {'name': 'Qatar', 'regex': r'^\d{5}$'},
    'RO': {'name': 'Romania', 'regex': r'^\d{6}$'},
    'RS': {'name': 'Serbia', 'regex': r'^\d{5}$'},
    'RU': {'name': 'Russia', 'regex': r'^\d{6}$'},
    'RW': {'name': 'Rwanda', 'regex': r'^$'},
    'SA': {'name': 'Saudi Arabia', 'regex': r'^\d{5}$'},
    'SB': {'name': 'Solomon Islands', 'regex': r'^$'},
    'SC': {'name': 'Seychelles', 'regex': r'^$'},
    'SD': {'name': 'Sudan', 'regex': r'^\d{5}$'},
    'SE': {'name': 'Sweden', 'regex': r'^\d{3}\s?\d{2}$'},
    'SG': {'name': 'Singapore', 'regex': r'^\d{6}$'},
    'SI': {'name': 'Slovenia', 'regex': r'^\d{4}$'},
    'SK': {'name': 'Slovakia', 'regex': r'^\d{3}\s?\d{2}$'},
    'SL': {'name': 'Sierra Leone', 'regex': r'^$'},
    'SM': {'name': 'San Marino', 'regex': r'^\d{5}$'},
    'SN': {'name': 'Senegal', 'regex': r'^\d{5}$'},
    'SR': {'name': 'Suriname', 'regex': r'^\d{5}$'},
    'ST': {'name': 'Sao Tome and Principe', 'regex': r'^$'},
    'SV': {'name': 'El Salvador', 'regex': r'^\d{4}$'},
    'SY': {'name': 'Syria', 'regex': r'^\d{5}$'},
    'SZ': {'name': 'Eswatini', 'regex': r'^\d{3}$'},
    'TD': {'name': 'Chad', 'regex': r'^$'},
    'TG': {'name': 'Togo', 'regex': r'^$'},
    'TH': {'name': 'Thailand', 'regex': r'^\d{5}$'},
    'TJ': {'name': 'Tajikistan', 'regex': r'^\d{6}$'},
    'TL': {'name': 'Timor-Leste', 'regex': r'^\d{5}$'},
    'TM': {'name': 'Turkmenistan', 'regex': r'^\d{6}$'},
    'TN': {'name': 'Tunisia', 'regex': r'^\d{4}$'},
    'TR': {'name': 'Turkey', 'regex': r'^\d{5}$'},
    'TT': {'name': 'Trinidad and Tobago', 'regex': r'^$'},
    'TW': {'name': 'Taiwan', 'regex': r'^\d{3}$'},
    'TZ': {'name': 'Tanzania', 'regex': r'^\d{5}$'},
    'UA': {'name': 'Ukraine', 'regex': r'^\d{5}$'},
    'UG': {'name': 'Uganda', 'regex': r'^$'},
    'US': {'name': 'United States', 'regex': r'^\d{5}(-\d{4})?$'},
    'UY': {'name': 'Uruguay', 'regex': r'^\d{5}$'},
    'UZ': {'name': 'Uzbekistan', 'regex': r'^\d{6}$'},
    'VC': {'name': 'Saint Vincent and the Grenadines', 'regex': r'^$'},
    'VE': {'name': 'Venezuela', 'regex': r'^\d{4}$'},
    'VN': {'name': 'Vietnam', 'regex': r'^\d{6}$'},
    'VU': {'name': 'Vanuatu', 'regex': r'^$'},
    'WS': {'name': 'Samoa', 'regex': r'^$'},
    'YE': {'name': 'Yemen', 'regex': r'^\d{5}$'},
    'ZA': {'name': 'South Africa', 'regex': r'^\d{4}$'},
    'ZM': {'name': 'Zambia', 'regex': r'^$'},
    'ZW': {'name': 'Zimbabwe', 'regex': r'^$'},
}

def get_postal_code_regex(country_code):
    country_code = country_code.upper()
    return POSTAL_CODE_DATA.get(country_code, {}).get('regex')

def validate_postal_code(postal_code, country_code):
    regex = get_postal_code_regex(country_code)
    if regex is None or regex == '^$':
        return True
    return re.match(regex, postal_code.strip().split('.')[0]) is not None

# if __name__ == "__main__":
#     # Test cases for a selection of countries
#     test_cases = [
#         ("12345", "US"),
#         ("12345-6789", "US"),
#         ("1267", "IN"),
#         ("K1A 0B1", "CA"),
#         ("GIR 0AA", "GB"),
#         ("WC2B 5AH", "GB"),
#         ("SP8 4XT", "IE"),
#         ("560100", "IN"),
#         ("123-4567", "JP"),
#         ("07412", "NZ"),
#         ("166 710", "CZ")
#     ]
    
#     for code, country in test_cases:
#         try:
#             valid = validate_postal_code(code, country)
#             country_name = POSTAL_CODE_DATA[country]['name']
#             print(f"Postal code '{code}' for {country_name} valid: {valid}")
#         except ValueError as e:
#             print(e)
